[[Inquiry-API]]
== Inquiry API

[[Inquiry-전체-조회]]
=== Inquiry 전체 조회
operation::inquiry-controller-test/get-all-inquiries[snippets='http-request,request-parameters,http-response,response-fields']

[[Inquiry-공개글-단건-조회]]
=== Inquiry 공개글 단건 조회
operation::inquiry-controller-test/get-public-inquiry[snippets='http-request,path-parameters,http-response,response-fields']

[[Inquiry-비밀글-단건-조회]]
=== Inquiry 비밀글 단건 조회
operation::inquiry-controller-test/get-private-inquiry[snippets='http-request,cookie-request-headers,path-parameters,request-parameters,http-response,response-fields']

[[Inquiry-등록]]
=== Inquiry 등록
operation::inquiry-controller-test/register-inquiry[snippets='http-request,cookie-request-headers,request-parts,request-part-inquiry-fields,http-response,response-headers']

[[Inquiry-수정]]
=== Inquiry 수정
operation::inquiry-controller-test/update-inquiry[snippets='http-request,cookie-request-headers,request-parts,request-part-inquiry-fields,http-response,response-headers']

[[Inquiry-삭제]]
=== Inquiry 삭제
operation::inquiry-controller-test/delete-inquiry[snippets='http-request,cookie-request-headers,http-response']