[[Photo-API]]
== Photo API

[[Photo-전체-조회]]
=== Photo 전체 조회
operation::photo-controller-test/get-all-photos[snippets='http-request,request-parameters,http-response,response-fields']

[[Photo-단건-조회]]
=== Photo 단건 조회
operation::photo-controller-test/get-photo[snippets='http-request,path-parameters,http-response,response-fields']

[[Photo-등록]]
=== Photo 등록
operation::photo-controller-test/register-photo[snippets='http-request,cookie-request-headers,request-parts,request-part-photo-fields,http-response,response-headers']

[[Photo-기존-이미지-수정]]
=== Photo 기존 이미지 수정
operation::photo-controller-test/update-photo_-edit-existing[snippets='http-request,cookie-request-headers,request-parts,request-part-photo-fields,request-parameters,http-response,response-headers']

[[Photo-새로운-이미지-추가]]
=== Photo 새로운 이미지 추가
operation::photo-controller-test/update-photo-add-new[snippets='http-request,cookie-request-headers,request-parts,request-part-photo-fields,http-response,response-headers']

[[Photo-삭제]]
=== Photo 삭제
operation::photo-controller-test/delete-photo[snippets='http-request,cookie-request-headers,http-response']